apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployments.yaml
  - service.yaml

# 이 부분이 나중에 GitHub Action에 의해 자동으로 업데이트됩니다.
images:
  - name: test-backend
    newName: ${{ secrets.AWS_REGISTRY }}/${{ secrets.AWS_REPOSITORY_PROD }}
    newTag: latest