name: NestJS Direct Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # 1. AWS 인증 (EKS 접근 권한 포함)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      # 2. ECR 로그인 및 이미지 빌드/푸시
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and Push Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_REPOSITORY_URL }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      # 3. Kustomize로 이미지 태그만 '임시'로 변경
      - name: Update Kubernetes Resources (In-memory)
        run: |
          cd k8s/prod
          kustomize edit set image test-backend=${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_REPOSITORY_URL }}:${{ github.sha }}

      # 4. EKS 클러스터 연결 설정 (kubeconfig 업데이트)
      - name: Update Kubeconfig
        run: |
          
          aws eks update-kubeconfig --region ap-northeast-2 --name dev-eks

      # 5. EKS에 즉시 배포 
      - name: Deploy to EKS
        run: |
          kubectl apply -k k8s/prod